name: ESTDS2020
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
timezone: Asia/Shanghai
livereload: true
baseurl: https://2020.estds.yicode.ac
cfrc_start: 2021-04-21
cfrc_end: 2021-04-24
cfrc_place: Nanjing, China
cfrc_place_zh: 中国·南京
