name: ESTDS2020 | Nanjing, China | 17~19 Sept. 2020
name_zh: ESTDS2020 | 中国·南京 | 2020年9月17~19日
sname: ESTDS2020
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
timezone: Asia/Shanghai
livereload: true
baseurl: https://estds.yicode.ac
