name: ESTDS2020
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
timezone: Asia/Shanghai
livereload: true
baseurl: https://estds.yicode.ac
cfrc_start: 2020-11-16
cfrc_end: 2020-11-19
cfrc_place: Nanjing, China
cfrc_place_zh: 中国·南京
